### ISSUE TITLE
Enables CORS with whitelisting

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex-org/coderplex-backend-old#1]
Currently we arent able to request resource outside of the domain. 
We are grabbing data from meetup api for our events page

**Comment by vinaypuppal** [comment]
`CORS` is already enabled see here 
https://github.com/coderplex/coderplex-backend/blob/e3c90fab51384ed77d89dfdbcd1c459ce3d3964a/src/app.js#L30
