### ISSUE TITLE
Dockerfile is using python 2.7

### ISSUE THREAD

**Issue by vinaypuppal** [coderplex-org/coderplex-backend-old#23]
* [x] I have searched the [issues](https://github.com/coderplex/coderplex/issues) of this repository and believe that this is not a duplicate.

# Expected Behavior
`Dockerfile`  should use same python version used for development

# Current Behavior
Readme and contribution guidelines mentioned this project uses `python 3.6` but `Dockerfile` contains 
https://github.com/coderplex/coderplex-backend/blob/b01296b807059cf3c4f4ccbf02e7a2929b136408/Dockerfile#L1-L3

**Comment by Prathamesh404** [comment]
Can we directly change the version name and make a PR?

**Comment by Prathamesh404** [comment]
I want to start contributing to the backend, let start from something miniscule

**Comment by M-ZubairAhmed** [comment]
you have to test the whole application if the python3 is not breaking the app

**Comment by pbteja1998** [comment]
Actually there is no need to check, entire app is written in `Python 3.6`  ,  so  `2.7` may fail but `3.6`  should not fail,if failed we should change the related code at which it fails.  So just changing `2.7` to `3.6` is enough.

**Comment by Prathamesh404** [comment]
You can close the issue as it the typo is fixed, looking forward to do a more meaningful contribution soon.
Thanks for the support and heads up.

**Comment by vinaypuppal** [comment]
fixed in #35
