### ISSUE TITLE
Admin dashboard is not able to load css files and other static files in production version

### ISSUE THREAD

**Issue by vinaypuppal** [coderplex-org/coderplex-backend-old#31]
* [x] I have searched the [issues](https://github.com/coderplex/coderplex/issues) of this repository and believe that this is not a duplicate.

I am testing `master` branch locally before deploying it to AWS. But admin dashboard css is not loading.

# Expected Behavior
- Admin dashboard should be able to load static files as it is loading in development environment

# Current Behavior
- Admin dashboard is not able to load css files and other static files.

## Steps to Reproduce (for bugs)
1. Append the following lines to `Dockerfile` as suggested by @pbteja1998 to create `superuser` during build.
   ```
     # Collect our static media.
    RUN python manage.py collectstatic --noinput
    RUN echo "from django.contrib.auth.models import User;User.objects.filter(username='coderplex').delete();User.objects.create_superuser('coderplex','dev@coderplex.org','coderplex')" | python manage.py shell | echo "user created"
    ```
1. And then run `docker-compose build` and `docker-compose up` 
1. Access `localhost:8000/admin` in browser.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| OS      |     osx    |
| docker |    17.09.0-ce     |

**Comment by vinaypuppal** [comment]
![screen shot 2017-12-03 at 13 05 43](https://user-images.githubusercontent.com/8843216/33523374-b893acc0-d82a-11e7-9d0c-47bc2584921d.png)

@rrmerugu Did we missing any configuration in Dockerfile

**Comment by rrmerugu** [comment]
@pbteja1998 Can you check https://docs.djangoproject.com/en/1.11/howto/static-files/#configuring-static-files . Configure  the below sections accordingly, It should work

```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]
```

**Comment by rrmerugu** [comment]
Also, Django is not designed to serve static files on its own, to serve the static files, generally we use a CDN or http://whitenoise.evans.io/en/stable/django.html  @pbteja1998

**Comment by vinaypuppal** [comment]
@pbteja1998 Any updates on this issue?

**Comment by pbteja1998** [comment]
No, I haven't looked into it. I don't think I can solve this problem, only @rrmerugu should be able to do it.
