### ISSUE TITLE
Create tasks

### ISSUE THREAD

**Issue by djsbalakrishnan** [coderplex-org/coderplex-backend-old#5]
Create a tasks file to organize the project like we discussed today.

**Comment by rrmerugu** [comment]
@djsbalakrishnan the information looks very  abstract, can you write down what tasks were discussed, I will add them accordingly

**Comment by djsbalakrishnan** [comment]
@rrmerugu we just discussed that you will give a split up of tasks so that the developers will exactly know what to work on. I see that you have done it now by creating issues. I am closing the issue now.
