### ISSUE TITLE
Create social login APIs with django-rest-social-auth

### ISSUE THREAD

**Issue by rrmerugu** [coderplex-org/coderplex-backend-old#6]
Generate social login APIs using https://github.com/st4lk/django-rest-social-auth . Ofcourse using JWT.

Implement github and linkedin authentication

**Comment by rrmerugu** [comment]
@duttakapil finalise what social logins do we support and update the description . I believe LinkedIn and Github for now?

**Comment by vinaypuppal** [comment]
@rrmerugu  Yes only github and linkedin.

**Comment by rrmerugu** [comment]
@gdhameeja do you think you take this ? this needs to be done before everything actually. otherwise, there is no point of creating user apis. without authentication

**Comment by gdhameeja** [comment]
I will take this up. Will let you know if I face issues.

**Comment by rrmerugu** [comment]
@gdhameeja  is this going good ?

**Comment by pbteja1998** [comment]
@rrmerugu I think you can close this issue now
