### ISSUE TITLE
Create UserProfile Model

### ISSUE THREAD

**Issue by rrmerugu** [coderplex-org/coderplex-backend-old#7]
Create a **UserProfile** data model that will have one-to-one relationship with the **User** Model of Django. 

UserProfile model will contain the extra information like bio, avatar, social links.
Reference : https://blog.khophi.co/extending-django-user-model-userprofile-like-a-pro/

The UserProfile should cover all the data which are specified in https://github.com/coderplex/coderplex/wiki/Release-Cycles#profiles--authentication

**Comment by djsbalakrishnan** [comment]
I will take up this issue.
