### ISSUE TITLE
Generate User APIs

### ISSUE THREAD

**Issue by rrmerugu** [coderplex-org/coderplex-backend-old#9]
1. View user profile GET /user/<user> 
2. Update profile POST /user/<user> 
3. Deactivate user POST /user/deactivate
4. Follow User user POST /user/follow

where <user> can be user_id or username, which ever we finalise .

**Comment by gdhameeja** [comment]
I will take this up.

**Comment by rrmerugu** [comment]
this tasks needs https://github.com/coderplex/coderplex-backend/pull/10  to be merged. waiting on it.
